name: xStaff
main: tk.ThePerkyTurkey.XStaff.XStaff
version: '1.1'
author: ThePerkyTurkey
softdepends: [MVdWPlaceholderAPI]

commands:
    report:
        usage: /report <player> <reason...>
        description: Reports a player for a given reason
        aliases: [xreport]
    staff:
        usage: /staff [player]
        description: Toggles staff mode for you or another player
        aliases: [staffmode, xstaff, xstaffmode]
    vanish:
        usage: /vanish [player]
        description: Toggles vanish mode for you or another player
        aliases: [v, xv, xvanish]
    reports:
        usage: /reports [player]
        description: Allows you to view all of the unresolved reports
        aliases: [xreports]
    freeze:
        usage: /freeze <player>
        description: Prevents a player from moving
        aliases: [xfreeze]
    details:
        usage: /details <player>
        description: Shows information about the player
        aliases: [examine, inspect, xdetails, xexamine, xinspect]
    warn:
        usage: /warn <player> <reason...>
        description: Warns the player
        aliases: [xwarn]
    warns:
        usage: /warns <player>
        description: Shows all of the player's warnings
        aliases: [xwarns]
    unwarn:
        usage: /unwarn <player> [id]
        description: Removes a player's warning
        aliases: [xunwarn]
    addnote:
        usage: /addnote <player> <note...>
        description: Adds a note to the player
        aliases: [xaddnote]
    notes:
        usage: /notes <player>
        description: Views a player's notes
        aliases: [xnotes]
    removenote:
        usage: /remnote <player> [id]
        description: Removes a player's note
        aliases: [xremovenote, remnote, xremnote]
    staffchat:
        usage: /schat [message]
        description: Toggles or sends a message in staff chat
        aliases: [xstaffchat, schat, xschat, sc, xsc]