name: xStaff
main: me.ThePerkyTurkey.XStaff.XStaff
version: '1.1'
author: ThePerkyTurkey

commands:
    report:
        usage: /report <player> <reason>
        description: Reports a player for a given reason
    staff:
        usage: /staff [player]
        description: Toggles staff mode for you or another player
    vanish:
        usage: /vanish [player]
        description: Toggles vanish mode for you or another player
        aliases: [v]
    reports:
        usage: /reports [player]
        description: Allows you to view all of the unresolved reports for a player
    freeze:
        usage: /freeze <player>
        description: Prevents a player from moving